*** Starting uWSGI 2.0.18 (64bit) on [Tue Aug 20 09:43:12 2019] ***
compiled with version: 7.4.0 on 15 August 2019 04:51:04
os: Linux-5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019
nodename: zhang-virtual-machine
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zhang/myproject/myproject
writing pidfile to /home/zhang/myproject/myproject//uwsgi/uwsgi.pid
open("/home/zhang/myproject/myproject//uwsgi/uwsgi.pid"): No such file or directory [core/utils.c line 3616]
*** Starting uWSGI 2.0.18 (64bit) on [Tue Aug 20 09:45:23 2019] ***
compiled with version: 7.4.0 on 15 August 2019 04:51:04
os: Linux-5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019
nodename: zhang-virtual-machine
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zhang/myproject/myproject
writing pidfile to /home/zhang/myproject/myproject//uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/zhang/myproject/myproject/
your processes number limit is 7595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8010 fd 3
uwsgi socket 0 bound to TCP address :8000 fd 6
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
Python main interpreter initialized at 0x559826011a40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./boards/models.py", line 10, in <module>
    class Topic(models.Model):
  File "./boards/models.py", line 13, in Topic
    board = models.ForeignKey(Board,related_name='topics')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2404)
spawned uWSGI worker 1 (pid: 2406, cores: 2)
spawned uWSGI worker 2 (pid: 2408, cores: 2)
spawned uWSGI worker 3 (pid: 2410, cores: 2)
Python auto-reloader enabled
spawned uWSGI worker 4 (pid: 2413, cores: 2)
*** Stats server enabled on /home/zhang/myproject/myproject//uwsgi/uwsgi.status fd: 18 ***
spawned uWSGI http 1 (pid: 2416)
--- no python application found, check your startup logs for errors ---
[pid: 2413|app: -1|req: -1/1] 192.168.100.1 () {40 vars in 834 bytes} [Tue Aug 20 01:45:36 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2413|app: -1|req: -1/2] 192.168.100.1 () {42 vars in 808 bytes} [Tue Aug 20 01:45:37 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2413|app: -1|req: -1/3] 192.168.100.1 () {40 vars in 834 bytes} [Tue Aug 20 01:45:41 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2413|app: -1|req: -1/4] 192.168.100.1 () {42 vars in 808 bytes} [Tue Aug 20 01:45:41 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2408|app: -1|req: -1/5] 192.168.100.1 () {38 vars in 815 bytes} [Tue Aug 20 01:45:50 2019] GET /board/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2413|app: -1|req: -1/6] 192.168.100.1 () {38 vars in 761 bytes} [Tue Aug 20 01:45:50 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 2416)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/zhang/myproject/myproject//uwsgi/uwsgi.status (stats) removed.
